### ISSUE TITLE
Mortality Prediction

### ISSUE THREAD

**Issue by Data-Designer** [pat-jj/KARE#1]
I noticed that the performance of its corresponding mortality prediction significantly outperforms that of Graphcare（reported in GraphCare）. Could this be attributed to differences in data processing? I didn't find any notable distinctions in data processing methods between the two in the paper.

**Comment by Data-Designer** [comment]
I found several explanations in your rebuttal for ICLR, but I still have a question. Is the macro F1 score/ Accuracy displayed here corresponding to the AUPRC/AUROC presented in the Graphcare paper?

I mean, did you simply output another metric for Graphcare in the same settings without retraining the model?

**Comment by pat-jj** [comment]
> I mean, did you simply output another metric for Graphcare in the same settings without retraining the model?

HI! Yes, in this work, we do not compare AUROC/AUPRC as they cannot be accurately computed for LLM predictions. So, we use accuracy/f1/sensitivity/specificity instead where the later two metrics are important to test model's ability on imbalanced datasets.
